version: "3.9"
services:
  postgres-service:
    image: postgres
    build:
      context: ./
      dockerfile: Dockerfile_postgres
    environment:
      POSTGRES_DB: "rcube"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres-service
    env_file:
      - env-variables.env